name: Application Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install -y libcurl4-openssl-dev

    - name: Configure CMake project for testing
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DDESKTOP=ON -DTEST=ON

    - name: Build CMake project for testing
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Execute tests
      working-directory: ${{ github.workspace }}/build
      run: |
        ctest --verbose
